version: '1.0'

services:
  backend:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - ".docker-compose.env"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node dist/server.js"
    container_name: attendance-backend
    image: lakhatekno/attendance-backend:1.0
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass_root123***
      - MYSQL_DATABASE=attendance
      - MYSQL_USER=attendance_admin
      - MYSQL_PASSWORD=password_cihuy123
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  db-data: