version: '1.0'

services:
  backend:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - ".docker-compose.env"
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass_root123***
      - MYSQL_DATABASE=attendance
      - MYSQL_USER=attendance_admin
      - MYSQL_PASSWORD=password_cihuy123
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: